package resources

import (
	"context"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/atensecurity/terraform-provider-thoth/internal/client"
	"github.com/atensecurity/terraform-provider-thoth/internal/tfhelpers"
)

var _ resource.Resource = &browserEnrollmentResource{}
var _ resource.ResourceWithImportState = &browserEnrollmentResource{}

type browserEnrollmentResource struct {
	client   *client.Client
	tenantID string
}

type browserEnrollmentModel struct {
	ID             types.String `tfsdk:"id"`
	TenantID       types.String `tfsdk:"tenant_id"`
	EnrollmentID   types.String `tfsdk:"enrollment_id"`
	Provider       types.String `tfsdk:"provider"`
	UserID         types.String `tfsdk:"user_id"`
	DeviceID       types.String `tfsdk:"device_id"`
	BrowserProfile types.String `tfsdk:"browser_profile"`
	Status         types.String `tfsdk:"status"`
	MetadataJSON   types.String `tfsdk:"metadata_json"`
	LastSeenAt     types.String `tfsdk:"last_seen_at"`
	CreatedAt      types.String `tfsdk:"created_at"`
	UpdatedAt      types.String `tfsdk:"updated_at"`
}

func NewBrowserEnrollmentResource() resource.Resource {
	return &browserEnrollmentResource{}
}

func (r *browserEnrollmentResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_browser_enrollment"
}

func (r *browserEnrollmentResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Manages browser enrollment records.",
		Attributes: map[string]schema.Attribute{
			"id":              schema.StringAttribute{Computed: true, Description: "Resource ID (enrollment ID).", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"tenant_id":       schema.StringAttribute{Computed: true, Description: "Tenant ID from provider configuration."},
			"enrollment_id":   schema.StringAttribute{Optional: true, Computed: true, Description: "Enrollment ID; generated by GovAPI if omitted."},
			"provider":        schema.StringAttribute{Required: true, Description: "Browser provider slug.", PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()}},
			"user_id":         schema.StringAttribute{Required: true, Description: "User identifier for enrollment."},
			"device_id":       schema.StringAttribute{Required: true, Description: "Device identifier for enrollment."},
			"browser_profile": schema.StringAttribute{Optional: true, Description: "Browser profile identifier."},
			"status":          schema.StringAttribute{Optional: true, Description: "Enrollment status (active, pending, disabled)."},
			"metadata_json":   schema.StringAttribute{Optional: true, Description: "Metadata JSON object."},
			"last_seen_at":    schema.StringAttribute{Optional: true, Description: "Last-seen timestamp (RFC3339)."},
			"created_at":      schema.StringAttribute{Computed: true, Description: "Creation timestamp."},
			"updated_at":      schema.StringAttribute{Computed: true, Description: "Update timestamp."},
		},
	}
}

func (r *browserEnrollmentResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	data := tfhelpers.RequireResourceClient(req, resp)
	if data == nil {
		return
	}
	r.client = data.Client
	r.tenantID = data.TenantID
}

func (r *browserEnrollmentResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan browserEnrollmentModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	next, ok := r.upsert(ctx, plan, plan, &resp.Diagnostics)
	if !ok {
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &next)...)
}

func (r *browserEnrollmentResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state browserEnrollmentModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	row, found, err := r.findEnrollment(ctx, state.EnrollmentID.ValueString(), state.Provider.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Error reading browser enrollment", err.Error())
		return
	}
	if !found {
		resp.State.RemoveResource(ctx)
		return
	}
	next := flattenBrowserEnrollment(row, state, r.tenantID)
	resp.Diagnostics.Append(resp.State.Set(ctx, &next)...)
}

func (r *browserEnrollmentResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan browserEnrollmentModel
	var state browserEnrollmentModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if (plan.EnrollmentID.IsNull() || plan.EnrollmentID.IsUnknown()) && !state.EnrollmentID.IsNull() && !state.EnrollmentID.IsUnknown() {
		plan.EnrollmentID = state.EnrollmentID
	}
	next, ok := r.upsert(ctx, plan, state, &resp.Diagnostics)
	if !ok {
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &next)...)
}

func (r *browserEnrollmentResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state browserEnrollmentModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	payload := map[string]any{
		"enrollment_id": state.EnrollmentID.ValueString(),
		"provider":      state.Provider.ValueString(),
		"user_id":       state.UserID.ValueString(),
		"device_id":     state.DeviceID.ValueString(),
		"status":        "disabled",
	}
	if !state.BrowserProfile.IsNull() && !state.BrowserProfile.IsUnknown() {
		payload["browser_profile"] = state.BrowserProfile.ValueString()
	}
	if !state.MetadataJSON.IsNull() && !state.MetadataJSON.IsUnknown() && strings.TrimSpace(state.MetadataJSON.ValueString()) != "" {
		obj, err := tfhelpers.ParseJSONObject(state.MetadataJSON.ValueString())
		if err == nil {
			payload["metadata"] = obj
		}
	}
	if !state.LastSeenAt.IsNull() && !state.LastSeenAt.IsUnknown() {
		payload["last_seen_at"] = state.LastSeenAt.ValueString()
	}
	_, err := r.client.UpsertBrowserEnrollment(ctx, payload)
	if err != nil {
		resp.Diagnostics.AddWarning("Failed to disable browser enrollment on delete", err.Error())
	}
}

func (r *browserEnrollmentResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	enrollmentID := strings.TrimSpace(req.ID)
	if enrollmentID == "" {
		resp.Diagnostics.AddError("Invalid import ID", "Use enrollment_id as import identifier.")
		return
	}
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), enrollmentID)...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("enrollment_id"), enrollmentID)...)
}

func (r *browserEnrollmentResource) upsert(ctx context.Context, plan, prior browserEnrollmentModel, diags *diag.Diagnostics) (browserEnrollmentModel, bool) {
	payload := map[string]any{
		"provider":  strings.TrimSpace(plan.Provider.ValueString()),
		"user_id":   strings.TrimSpace(plan.UserID.ValueString()),
		"device_id": strings.TrimSpace(plan.DeviceID.ValueString()),
	}
	if payload["provider"] == "" {
		diags.AddAttributeError(path.Root("provider"), "Missing provider", "provider must be set.")
		return browserEnrollmentModel{}, false
	}
	if payload["user_id"] == "" {
		diags.AddAttributeError(path.Root("user_id"), "Missing user_id", "user_id must be set.")
		return browserEnrollmentModel{}, false
	}
	if payload["device_id"] == "" {
		diags.AddAttributeError(path.Root("device_id"), "Missing device_id", "device_id must be set.")
		return browserEnrollmentModel{}, false
	}
	if !plan.EnrollmentID.IsNull() && !plan.EnrollmentID.IsUnknown() {
		payload["enrollment_id"] = plan.EnrollmentID.ValueString()
	} else if !prior.EnrollmentID.IsNull() && !prior.EnrollmentID.IsUnknown() {
		payload["enrollment_id"] = prior.EnrollmentID.ValueString()
	}
	if !plan.BrowserProfile.IsNull() && !plan.BrowserProfile.IsUnknown() {
		payload["browser_profile"] = plan.BrowserProfile.ValueString()
	}
	if !plan.Status.IsNull() && !plan.Status.IsUnknown() {
		payload["status"] = plan.Status.ValueString()
	}
	if !plan.LastSeenAt.IsNull() && !plan.LastSeenAt.IsUnknown() {
		payload["last_seen_at"] = plan.LastSeenAt.ValueString()
	}
	if !plan.MetadataJSON.IsNull() && !plan.MetadataJSON.IsUnknown() && strings.TrimSpace(plan.MetadataJSON.ValueString()) != "" {
		obj, err := tfhelpers.ParseJSONObject(plan.MetadataJSON.ValueString())
		if err != nil {
			diags.AddAttributeError(path.Root("metadata_json"), "Invalid JSON", err.Error())
			return browserEnrollmentModel{}, false
		}
		payload["metadata"] = obj
	}

	row, err := r.client.UpsertBrowserEnrollment(ctx, payload)
	if err != nil {
		diags.AddError("Error upserting browser enrollment", err.Error())
		return browserEnrollmentModel{}, false
	}
	return flattenBrowserEnrollment(row, plan, r.tenantID), true
}

func (r *browserEnrollmentResource) findEnrollment(ctx context.Context, enrollmentID, provider string) (map[string]any, bool, error) {
	rows, err := r.client.ListBrowserEnrollments(ctx, provider, "")
	if err != nil {
		return nil, false, err
	}
	row, found := tfhelpers.FindByStringField(rows, "enrollment_id", enrollmentID)
	return row, found, nil
}

func flattenBrowserEnrollment(row map[string]any, current browserEnrollmentModel, tenantID string) browserEnrollmentModel {
	next := current
	enrollmentID := tfhelpers.GetString(row, "enrollment_id")
	next.ID = types.StringValue(enrollmentID)
	next.EnrollmentID = types.StringValue(enrollmentID)
	next.TenantID = types.StringValue(tenantID)
	next.Provider = nullableString(row, "provider")
	next.UserID = nullableString(row, "user_id")
	next.DeviceID = nullableString(row, "device_id")
	next.BrowserProfile = nullableString(row, "browser_profile")
	next.Status = nullableString(row, "status")
	if raw := row["metadata"]; raw != nil {
		next.MetadataJSON = types.StringValue(tfhelpers.ToJSONString(raw))
	}
	next.LastSeenAt = nullableString(row, "last_seen_at")
	next.CreatedAt = nullableString(row, "created_at")
	next.UpdatedAt = nullableString(row, "updated_at")
	return next
}
