# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

project_name: terraform-provider-thoth

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - id: terraform-provider-thoth
    binary: terraform-provider-thoth_v{{ .Version }}
    main: .
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w -X github.com/atensecurity/terraform-provider-thoth.version={{ .Version }}
    mod_timestamp: "{{ .CommitTimestamp }}"
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64

archives:
  - id: provider-binaries
    formats: ["zip"]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_SHA256SUMS"

changelog:
  disable: true

signs:
  - artifacts: checksum
    args:
      - --batch
      - --pinentry-mode
      - loopback
      - --passphrase
      - "{{ .Env.GPG_PASSPHRASE }}"
      - --local-user
      - "{{ .Env.GPG_FINGERPRINT }}"
      - --output
      - "${signature}"
      - --detach-sign
      - "${artifact}"

release:
  prerelease: auto
  mode: replace
  header: |
    {{- if .Env.RELEASE_NOTES -}}
    {{ .Env.RELEASE_NOTES }}
    {{- else -}}
    See CHANGELOG.md for release details.
    {{- end }}
