package data_sources

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/atensecurity/terraform-provider-thoth/internal/client"
	"github.com/atensecurity/terraform-provider-thoth/internal/tfhelpers"
)

const defaultMCPDigestWindowHours int64 = 24 * 7

var _ datasource.DataSource = &mcpInventoryDigestDataSource{}

type mcpInventoryDigestDataSource struct {
	client *client.Client
}

type mcpInventoryDigestDataSourceModel struct {
	WindowHours         types.Int64  `tfsdk:"window_hours"`
	TotalEndpoints      types.Int64  `tfsdk:"total_endpoints"`
	UnapprovedEndpoints types.Int64  `tfsdk:"unapproved_endpoints"`
	UnapprovedCalls     types.Int64  `tfsdk:"unapproved_calls"`
	TopUnapprovedJSON   types.String `tfsdk:"top_unapproved_endpoints_json"`
	RecommendedActions  types.List   `tfsdk:"recommended_actions"`
	ResponseJSON        types.String `tfsdk:"response_json"`
}

func NewMCPInventoryDigestDataSource() datasource.DataSource {
	return &mcpInventoryDigestDataSource{}
}

func (d *mcpInventoryDigestDataSource) Metadata(
	_ context.Context,
	req datasource.MetadataRequest,
	resp *datasource.MetadataResponse,
) {
	resp.TypeName = req.ProviderTypeName + "_mcp_inventory_digest"
}

func (d *mcpInventoryDigestDataSource) Schema(
	_ context.Context,
	_ datasource.SchemaRequest,
	resp *datasource.SchemaResponse,
) {
	resp.Schema = schema.Schema{
		Description: "Reads MCP inventory digest with top unapproved endpoints and remediation actions.",
		Attributes: map[string]schema.Attribute{
			"window_hours": schema.Int64Attribute{
				Optional:    true,
				Computed:    true,
				Description: "Digest lookback window in hours. Defaults to 168.",
			},
			"total_endpoints": schema.Int64Attribute{
				Computed:    true,
				Description: "Total endpoints observed in the digest window.",
			},
			"unapproved_endpoints": schema.Int64Attribute{
				Computed:    true,
				Description: "Endpoints with one or more unapproved MCP calls.",
			},
			"unapproved_calls": schema.Int64Attribute{
				Computed:    true,
				Description: "Total unapproved MCP calls in the digest window.",
			},
			"top_unapproved_endpoints_json": schema.StringAttribute{
				Computed:    true,
				Description: "Top unapproved endpoint rows as JSON array.",
			},
			"recommended_actions": schema.ListAttribute{
				Computed:    true,
				ElementType: types.StringType,
				Description: "Recommended actions generated by GovAPI.",
			},
			"response_json": schema.StringAttribute{
				Computed:    true,
				Description: "Digest payload as JSON.",
			},
		},
	}
}

func (d *mcpInventoryDigestDataSource) Configure(
	_ context.Context,
	req datasource.ConfigureRequest,
	resp *datasource.ConfigureResponse,
) {
	data := tfhelpers.RequireDataSourceClient(req, resp)
	if data == nil {
		return
	}
	d.client = data.Client
}

func (d *mcpInventoryDigestDataSource) Read(
	ctx context.Context,
	req datasource.ReadRequest,
	resp *datasource.ReadResponse,
) {
	var state mcpInventoryDigestDataSourceModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	windowHours := defaultMCPDigestWindowHours
	if !state.WindowHours.IsNull() && !state.WindowHours.IsUnknown() && state.WindowHours.ValueInt64() > 0 {
		windowHours = state.WindowHours.ValueInt64()
	}

	result, err := d.client.GetMCPInventoryDigest(ctx, windowHours)
	if err != nil {
		resp.Diagnostics.AddError("Error reading MCP inventory digest", err.Error())
		return
	}

	topRows := []map[string]any{}
	if rawRows, ok := result["top_unapproved_endpoints"].([]any); ok {
		topRows = make([]map[string]any, 0, len(rawRows))
		for _, raw := range rawRows {
			if row, ok := raw.(map[string]any); ok {
				topRows = append(topRows, row)
			}
		}
	}
	state.WindowHours = types.Int64Value(tfhelpers.GetInt64(result, "window_hours"))
	state.TotalEndpoints = types.Int64Value(tfhelpers.GetInt64(result, "total_endpoints"))
	state.UnapprovedEndpoints = types.Int64Value(tfhelpers.GetInt64(result, "unapproved_endpoints"))
	state.UnapprovedCalls = types.Int64Value(tfhelpers.GetInt64(result, "unapproved_calls"))
	state.TopUnapprovedJSON = types.StringValue(tfhelpers.ToJSONArrayString(topRows))
	state.RecommendedActions = tfhelpers.StringSliceValue(tfhelpers.GetStringSlice(result, "recommended_actions"))
	state.ResponseJSON = types.StringValue(tfhelpers.ToJSONString(result))

	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}
